[program:poster]
command=/opt/poster-py/bin/python /www/wwwroot/poster.ms1001.com/server.py
directory=/www/wwwroot/poster.ms1001.com
user=www
autostart=true
autorestart=true
startsecs=3
stopwaitsecs=30
redirect_stderr=true
stdout_logfile=/www/wwwlogs/poster_supervisor.log
environment=HOST="127.0.0.1",PORT="8010",POSTER_SECURE_COOKIE="1"
